### ISSUE TITLE
Have you ever considered to add 'html' as an element?

### ISSUE THREAD

**Issue by panzhongxian** [Airmanbzh/php-html-generator#10]
Thanks for your simple but powerful code.

I am a beginner in php and web. I changed your code to a CodeIgniter library class so that I can use conveniently. I also add a tiny code to prettify the html code.  And I fount that it can not generate an html head. 

can we add these features in?

**Comment by Airmanbzh** [comment]
Maybe I don't understand but you can generate any tag with these classes (even the most exotics ones). So if you want to generate an head tag you have to do like this :

$html = HtmlTag::createElement('html');
$head = $html->addElement('head');

$head->addElement('title')->text('Your title');
$head->addElement('exoticTag')->text('I\'m an exotic tag in the head of html');
