### ISSUE TITLE
No showTextBeforeContent() method

### ISSUE THREAD

**Issue by dymoksc** [Airmanbzh/php-html-generator#2]
Thank you for HtmlTag, I'm using it a lot in the current project of mine, it has already saved me a bunch of time. I just wanted to point out, that I wasn't unfortunately able to find showTextBeforeContent() method mentioned in the project documentation in any of two classes.

**Comment by jarodium** [comment]
Hello there.
Is it possible to add a text node after an input type = checkbox?
Here is what I am trying to reproduce:


```html
<div class="checkbox">
     <label>
         <input type="checkbox"> Remember me
    </label>
</div>
```

I'm using this:
 ```php
$lembrar = HtmlTag::createElement('div')->addClass("checkbox");
$label = $lembrar->addElement("label");
    //the input_checks function returns an input element also created with this class, but does not work
$label->addElement($this->input_checks($checks))->text("Remember me");
    //I have to take an extra tag after the element to provide the text I need to ouput
  //$label->addElement("span")->text("teste");
```
If I use the text() function before I add the checkbox, it will display before, but not after, which is what I intend to do.

Thanks for the great class. 
Regards

**Comment by Airmanbzh** [comment]
Hello,

When you do this : $label->addElement(XYZ)->text('your text'). You add the text to the 'input' instead of the label. 

To add your text to the label element :
```php
$lembrar = HtmlTag::createElement('div')->addClass("checkbox");

$label = $lembrar->addElement("label");
    //the input_checks function returns an input element also created with this class, but does not work
$input = $this->input_checks($checks);

$label->addElement($input);
$label->text("Remember me");
```

Or this : 
```php
$lembrar = HtmlTag::createElement('div')->addClass("checkbox");

$label = $lembrar->addElement("label");
//the input_checks function returns an input element also created with this class, but does not work
$label->addElement($this->input_checks($checks))
    ->getParent()
    ->text("Remember me");
```

In addition, if you allow me, you should'nt use 'label' like this to respect w3c recommendations. Instead, try something like that (if you can) :
```html
<div class="checkbox">
     <input id="checkBoxId" type="checkbox"/>
    <label for="checkBoxId>Remember me</label>
</div>
```

**Comment by jarodium** [comment]
Thanks. 
The getParent() solution worked.
I agree with you with the w3c recommendation, but unfortunately I am strictly following the code on the template I am working with. I don't want to make changes to the css or else I have to do a lot of work, ehehehe.

Thank you for the help
Regards :D
