### ISSUE TITLE
Make the package stable for Composer

### ISSUE THREAD

**Issue by natepage** [Airmanbzh/php-html-generator#20]
Hi,

I used your package in my last project [EasyHtmlElement](https://github.com/natepage/easy-html-element) and first thank you your code is useful! :)

But when I tried to integrate it to some frameworks and libraries I had an issue. Your code doesn't have any releases so composer considered your code isn't stable. If we want to use your code in a composer project we have to modify the `minimum-stability` to dev and we may get unstable versions of all packages.

So could you create a release please, `v1.0.0` for example, to allows all composer users to use your code in their projects?

Thank you! :)

**Comment by Airmanbzh** [comment]
Hi,

You're right, I totally forgot to specify a stable release. Thanks to remind me this :). It's done now.

**Comment by natepage** [comment]
Nice!

And when I see "bzh" I just want to say, merci la bretagne ! ahah
