### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by eff-one** [Airmanbzh/php-html-generator#26]
In Readme:

**ID (method : 'id')**
```
$tag = $html->tag('div')
	->id('myID');
echo( $tag );
// <div id='myID'>my link</a>
```
Does a `<div>` really close with `</a> `?

**Comment by Airmanbzh** [comment]
#27 

Yeap, my bad ! 
Thanks to pointing it to me ! A pull request is waiting to correct It :)

**Comment by Airmanbzh** [comment]
it's corrected

**Comment by eff0ne** [comment]
Also I don't see `$html->text('my link');` is assigned, but its there in output.

**Comment by Airmanbzh** [comment]
Yeah, I saw it to when I was correcting the first error and I'm on it now :)

**Comment by Airmanbzh** [comment]
#29 
Corrected too :)
