### ISSUE TITLE
Add this package to packagist

### ISSUE THREAD

**Issue by timsamuelsson** [Airmanbzh/php-html-generator#9]
Hi,

Looks like a nice class!
I would be very happy if you could add the repo to Packagist.

//Tim

**Comment by Airmanbzh** [comment]
Actually, it's already exist on packagist

See : https://github.com/Airmanbzh/php-html-generator/issues/5

And the page of packagist : https://packagist.org/packages/airmanbzh/php-html-generator

**Comment by timsamuelsson** [comment]
Oh,,, My bad... Thanks alot for a great class!

**Comment by Airmanbzh** [comment]
You're welcome ;)

And thanks :)
